#pragma once

#include <cstddef>
#include <cstdint>

// The gzipped airport typeahead payload, embedded via
// `board_build.embed_files = data/airport_index.json.gz` in platformio.ini.
// Regenerated by `python3 scripts/build_web_data.py`. Trimmed row shape:
//   [icao, iata, city, lat, lon]
extern const uint8_t _binary_data_airport_index_json_gz_start[] asm(
    "_binary_data_airport_index_json_gz_start");
extern const uint8_t _binary_data_airport_index_json_gz_end[] asm(
    "_binary_data_airport_index_json_gz_end");

namespace plane_radar::portal {

// HTML/JS injected into every WiFiManager page via setCustomHeadElement().
//
// On EVERY page: kills iOS's initial auto-capitalization on the Wi-Fi password
//   and SSID fields.
// On the LAN /param page: groups WiFiManager's flat list of fields into named
//   sections with hint text, adds address+airport search boxes wired to a
//   local airport index + the Netlify geocode proxy, replaces the focus-list
//   raw-JSON field with an editable chip list, and auto-populates empty home
//   coords via a public IP-geolocation call on first load.
// On the captive-portal /param page (we deliberately don't attach any params
//   there), the enhancement is a no-op past the caps fix.
constexpr char kCustomHead[] = R"HTML(<style>
.pr-sec{margin:18px 0 6px}
.pr-hdr{font-size:1.1em;font-weight:700;border-bottom:1px solid #ccc;padding-bottom:3px;margin-bottom:4px}
.pr-hint{color:#666;font-size:.85em;margin-bottom:8px}
.pr-search{position:relative}
.pr-hits{display:none;position:absolute;left:0;right:0;top:100%;z-index:10;border:1px solid #ccc;border-top:none;max-height:220px;overflow:auto;font-size:.9em;background:#fff;border-radius:0 0 .3rem .3rem;box-shadow:0 3px 10px rgba(0,0,0,.1)}
.pr-hit{padding:8px 10px;cursor:pointer;border-bottom:1px solid #eee}
.pr-hit:hover{background:#e8f4fe}
.pr-hit:last-child{border-bottom:0}
.pr-chip{border:1px solid #ccc;border-radius:.3rem;padding:4px 4px 4px 8px;display:inline-flex;align-items:center;gap:6px;background:#f4f7fa;margin:0 4px 4px 0}
.pr-chip-name{border:0;background:transparent;font-weight:700;font-size:1em;width:5em;padding:2px 0}
.pr-chip-name:focus{outline:1px solid #1fa3ec;border-radius:2px}
.pr-chip-range{width:4.6em;padding:2px 4px;font-size:.9em;margin:0}
.pr-chip-rm{padding:2px 8px;background:#dc3630;color:#fff;border:0;border-radius:.3rem;cursor:pointer;font-size:1em;line-height:1}
body.invert .pr-hits{background:#282828;border-color:#555}
body.invert .pr-hit{border-bottom-color:#444}
body.invert .pr-hit:hover{background:#3a3a3a}
body.invert .pr-chip{background:#282828;border-color:#555}
body.invert .pr-hdr{border-bottom-color:#555}
body.invert .pr-hint{color:#aaa}
</style><script>
(function(){
"use strict";
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
function deb(fn,ms){var t;return function(){var a=arguments,c=this;clearTimeout(t);t=setTimeout(function(){fn.apply(c,a);},ms);};}
function el(tag,attrs,inner){var e=document.createElement(tag);if(attrs)for(var k in attrs)e.setAttribute(k,attrs[k]);if(inner!=null)e.innerHTML=inner;return e;}

// Kill iOS's initial auto-caps on password and SSID fields.
function fixCaps(){
  document.querySelectorAll('input[type=password], input[name=s], input[name=ssid]').forEach(function(x){
    x.setAttribute("autocapitalize","off");
    x.setAttribute("autocorrect","off");
    x.setAttribute("spellcheck","false");
  });
}

// Cached lazy fetch of the trimmed airport index served from device flash.
var apIdxP=null;
function apIdx(){
  if(apIdxP) return apIdxP;
  apIdxP=fetch("/data/airport_index.json").then(function(r){return r.ok?r.json():[];}).catch(function(){return[];});
  return apIdxP;
}
// Row shape: [icao, iata, city, lat, lon]. Airport picks always carry the
// ICAO as the chip name — consistent 4-letter identifier worldwide.
function apSearch(idx,q){
  q=q.toLowerCase();var out=[];
  for(var i=0;i<idx.length&&out.length<8;i++){
    var r=idx[i],ic=(r[0]||"").toLowerCase(),ia=(r[1]||"").toLowerCase(),ci=(r[2]||"").toLowerCase();
    var hit=ic===q||ia===q||ic.indexOf(q)===0||ia.indexOf(q)===0||ci.indexOf(q)===0||ci.indexOf(q)>=0;
    if(hit) out.push({
      label:(r[1]?r[1]+" · ":"")+r[0]+" — "+r[2],
      lat:r[3],lon:r[4],
      chipName:r[0],                     // ICAO — canonical airport ID
      fullText:r[0]+" — "+r[2]           // shown in search box after pick
    });
  }
  return out;
}

// Address geocoding via the Netlify proxy. Show the whole display_name in the
// search box (users typed an address — they want to see the address); derive a
// short chip name from a middle segment (skip the street number; pick the
// most human-readable label available).
function addrShortName(displayName){
  var parts=displayName.split(",").map(function(s){return s.trim();}).filter(Boolean);
  if(!parts.length) return "Place";
  // Skip a pure-number first segment (house number) — pick the next thing.
  var i=(/^\d+$/.test(parts[0]))?1:0;
  var pick=parts[i]||parts[0];
  return pick.length>16?pick.slice(0,16):pick;
}
function addrSearch(q,sig){
  return fetch("https://radar.benyaffe.com/api/geocode?q="+encodeURIComponent(q),{signal:sig})
    .then(function(r){return r.ok?r.json():[];})
    .then(function(rows){return rows.slice(0,5).map(function(x){return{
      label:"📍 "+x.display_name,
      lat:x.lat,lon:x.lon,
      chipName:addrShortName(x.display_name),
      fullText:x.display_name
    };});})
    .catch(function(){return[];});
}
function search(q){
  if(q.length<2) return Promise.resolve([]);
  var ac=new AbortController();
  return Promise.all([
    apIdx().then(function(i){return apSearch(i,q);}),
    q.length>=3?addrSearch(q,ac.signal):Promise.resolve([])
  ]).then(function(rs){return rs[0].concat(rs[1]);});
}

// --- section helpers ---
function makeSection(title,hint){
  var wrap=el("div",{"class":"pr-sec"});
  wrap.appendChild(el("div",{"class":"pr-hdr"},esc(title)));
  if(hint) wrap.appendChild(el("div",{"class":"pr-hint"},esc(hint)));
  return wrap;
}
function makeSearchBox(placeholder){
  var box=el("div",{"class":"pr-search"});
  box.innerHTML=
    '<input type="text" placeholder="'+esc(placeholder)+'" autocapitalize="off" autocorrect="off" spellcheck="false">'+
    '<div class="pr-hits"></div>';
  return box;
}
// Walk back past <br>s to find the <label for=id> WiFiManager emits before
// text-input fields (label-BEFORE pattern). Rejects labels belonging to a
// different field — checkboxes use label-AFTER, so their `previous` chain
// leads to the prior field's label, which is not what we want.
function labelFor(input){
  var e=input.previousElementSibling;
  while(e && e.tagName==="BR") e=e.previousElementSibling;
  if(e && e.tagName==="LABEL" && e.getAttribute("for")===input.id) return e;
  return null;
}
// The anchor before which we insert section stuff:
//   - label-BEFORE fields  → the label (header lands above the label)
//   - label-AFTER / bare   → the input's own preceding <br>, else the input
function anchorFor(input){
  var lbl=labelFor(input);
  if(lbl) return lbl;
  var prev=input.previousElementSibling;
  if(prev && prev.tagName==="BR") return prev;
  return input;
}
function renderHits(hits,results,pick){
  if(!results.length){hits.style.display="none";hits.innerHTML="";return;}
  hits.innerHTML=results.map(function(r,i){return '<div class="pr-hit" data-i="'+i+'">'+esc(r.label)+'</div>';}).join("");
  hits.style.display="block";
  hits.querySelectorAll(".pr-hit").forEach(function(x){
    x.addEventListener("click",function(){pick(results[+x.getAttribute("data-i")]);});
  });
}

// Insert a section header + search box above the coord pair.
function decorateCoordPair(latEl,lonEl,title,hint){
  var anchor=anchorFor(latEl);
  var sec=makeSection(title,hint);
  var box=makeSearchBox("Search address or airport (e.g. SFO, Golden Gate Bridge)");
  sec.appendChild(box);
  anchor.parentNode.insertBefore(sec,anchor);
  var input=box.querySelector("input"),hits=box.querySelector(".pr-hits");
  var run=deb(function(){
    search(input.value.trim()).then(function(rs){
      renderHits(hits,rs,function(r){
        latEl.value=Number(r.lat).toFixed(6);
        lonEl.value=Number(r.lon).toFixed(6);
        input.value=r.fullText;
        hits.style.display="none";
        latEl.dispatchEvent(new Event("input"));
        lonEl.dispatchEvent(new Event("input"));
      });
    });
  },300);
  input.addEventListener("input",run);
  document.addEventListener("click",function(e){if(!sec.contains(e.target)) hits.style.display="none";});
}

// Focus places editor: chip list + add-search. Serializes back to the hidden
// WiFiManager textarea on every change. Chip name is user-editable inline —
// airports get ICAO by default, addresses get a short human name.
function decorateFocusEditor(field){
  var anchor=anchorFor(field);
  var sec=makeSection("Focus places","Extra spots the radar cycles through with a double-tap.");
  var chips=el("div",null,"");chips.style.marginBottom="6px";
  sec.appendChild(chips);
  var box=makeSearchBox("Add airport or address (e.g. PAO, Golden Gate Bridge)");
  sec.appendChild(box);
  anchor.parentNode.insertBefore(sec,anchor);
  // Hide the raw JSON field + its label — chips are the source of truth from
  // the user's perspective; the field is a hidden save-handler pipe.
  if(anchor.tagName==="LABEL") anchor.style.display="none";
  field.style.display="none";

  var rng=[5,10,15,25]; // matches kRangePresets in include/ui/radar_range.h
  var arr=[];
  try{arr=JSON.parse(field.value||"[]");if(!Array.isArray(arr))arr=[];}catch(e){arr=[];}

  function ser(){
    field.value=JSON.stringify(arr.map(function(e){return{
      name:String(e.name||"").slice(0,16),
      lat:+Number(e.lat).toFixed(6),
      lon:+Number(e.lon).toFixed(6),
      range_idx:e.range_idx|0
    };}));
  }
  function draw(){
    chips.innerHTML="";
    arr.forEach(function(e,i){
      var chip=el("span",{"class":"pr-chip","data-i":i});
      var opts=rng.map(function(nm,ri){return '<option value="'+ri+'"'+(ri===(e.range_idx|0)?" selected":"")+">"+nm+"nm</option>";}).join("");
      chip.innerHTML=
        '<input class="pr-chip-name" value="'+esc(e.name)+'" maxlength="16" autocapitalize="off" autocorrect="off" spellcheck="false">'+
        '<select class="pr-chip-range">'+opts+'</select>'+
        '<button type="button" class="pr-chip-rm" title="Remove">×</button>';
      chip.querySelector(".pr-chip-name").addEventListener("input",function(ev){
        arr[i].name=ev.target.value;ser();
      });
      chip.querySelector(".pr-chip-range").addEventListener("change",function(ev){
        arr[i].range_idx=+ev.target.value;ser();
      });
      chip.querySelector(".pr-chip-rm").addEventListener("click",function(){
        arr.splice(i,1);draw();ser();
      });
      chips.appendChild(chip);
    });
  }
  draw();ser();

  var input=box.querySelector("input"),hits=box.querySelector(".pr-hits");
  var run=deb(function(){
    search(input.value.trim()).then(function(rs){
      renderHits(hits,rs,function(r){
        arr.push({
          name:r.chipName,
          lat:+Number(r.lat).toFixed(6),
          lon:+Number(r.lon).toFixed(6),
          range_idx:1
        });
        input.value="";hits.style.display="none";draw();ser();
      });
    });
  },300);
  input.addEventListener("input",run);
  document.addEventListener("click",function(e){if(!sec.contains(e.target)) hits.style.display="none";});
}

// Insert a header before a label-anchored element. Used to bracket sections
// that already have working WiFiManager fields (weather reach, layers, device).
function insertHeaderBefore(anchor,title,hint){
  if(!anchor) return;
  var sec=makeSection(title,hint);
  anchor.parentNode.insertBefore(sec,anchor);
}

// Auto-populate empty home coords via public IP geolocation. Best-effort;
// silent on failure. Runs once at page load, only if coords look unset.
function autoLocate(latEl,lonEl){
  if(!latEl||!lonEl) return;
  var la=parseFloat(latEl.value),lo=parseFloat(lonEl.value);
  if(!isNaN(la)&&!isNaN(lo)&&!(la===0&&lo===0)) return;
  fetch("https://ipapi.co/json/").then(function(r){return r.ok?r.json():null;}).then(function(d){
    if(!d||typeof d.latitude!=="number"||typeof d.longitude!=="number") return;
    if(parseFloat(latEl.value)===0||latEl.value==="") latEl.value=d.latitude.toFixed(6);
    if(parseFloat(lonEl.value)===0||lonEl.value==="") lonEl.value=d.longitude.toFixed(6);
  }).catch(function(){});
}

function init(){
  fixCaps();
  var lh=document.querySelector("input[name=radar_lat]");
  var oh=document.querySelector("input[name=radar_lon]");
  var lm=document.querySelector("input[name=metar_lat]");
  var om=document.querySelector("input[name=metar_lon]");
  var rm=document.querySelector("input[name=metar_rad]");
  var fr=document.querySelector("textarea[name=focus_ring],input[name=focus_ring]");
  var lyr1=document.querySelector("input[name=lyr_coast]");
  var host=document.querySelector("input[name=ota_host]");

  if(lh&&oh) decorateCoordPair(lh,oh,"Home","Where the radar is centered by default.");
  if(lm&&om) decorateCoordPair(lm,om,"Weather map","Which airports show weather colors on the weather view.");
  // Prepend a hint above the reach field, which has its own label already.
  if(rm){
    var reachAnchor=anchorFor(rm);
    var hint=el("div",{"class":"pr-hint"},"How far the weather map reaches from that center.");
    reachAnchor.parentNode.insertBefore(hint,reachAnchor);
  }
  if(fr) decorateFocusEditor(fr);
  if(lyr1) insertHeaderBefore(anchorFor(lyr1),"Map layers","Turn each overlay on or off.");
  if(host) insertHeaderBefore(anchorFor(host),"Device","Advanced. Change this if you have more than one radar on your network.");

  if(lh&&oh) autoLocate(lh,oh);
}

if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",init); else init();
})();
</script>)HTML";

}  // namespace plane_radar::portal
