#pragma once

#include <cstddef>
#include <cstdint>

// The gzipped airport typeahead payload, embedded via
// `board_build.embed_files = data/airport_index.json.gz` in platformio.ini.
// Regenerated by `python3 scripts/build_web_data.py`. Trimmed row shape:
//   [icao, iata, city, lat, lon]
extern const uint8_t _binary_data_airport_index_json_gz_start[] asm(
    "_binary_data_airport_index_json_gz_start");
extern const uint8_t _binary_data_airport_index_json_gz_end[] asm(
    "_binary_data_airport_index_json_gz_end");

namespace plane_radar::portal {

// HTML/JS/CSS injected into every WiFiManager page.
//
// Split into three constants because WiFiManager's page renderer does
// `page += _customHeadElement` (Arduino String concat). Injecting the
// full 20 KB inline forces a heap alloc that grows to ~32 KB — after
// the 58 KB frame sprite is pre-allocated at boot, the largest
// contiguous free block frequently isn't that big, and the String
// silently drops the append. That produced the "back to raw JSON /
// duplicate Latitude labels / no chip editor" regression on /param.
//
// Solution: `kCustomHead` is now a tiny `<link>+<script>` bootstrap
// that WM inlines (no allocation pressure). The heavy CSS/JS bodies
// live in `kCustomCss` / `kCustomJs` and are served from `/pr.css`
// and `/pr.js` by wifi_setup.cpp via `send_P` — streams from flash,
// no big String required.
//
// On EVERY page:
//   - kill iOS auto-caps on password / SSID fields
//   - replace the h1 with "Plane Radar" (LAN) or "Plane Radar Setup" (AP)
//
// On the LAN /param page only:
//   - fold the flat field list into named sections with hint lines
//     ("Home", "Weather map", "Focus places", "Map layers", "Device")
//   - address+airport search box above each coord pair, populating lat/lon
//   - focus-places chip editor (one column, editable name, editable range,
//     wrap subtitle for freshly picked addresses); auto-migrates 3-letter
//     IATA names to 4-letter ICAO via the local airport index
//   - intercepts the form submit to POST in place — no more dead-end
//     "Saved" page, just a green banner and stay put
//   - auto-populates empty home coords via ipapi.co on first load

// Injected into every page's <head>. Loads the heavier assets via
// separate GETs so nothing large ends up in WM's response String.
constexpr char kCustomHead[] =
    "<link rel=\"stylesheet\" href=\"/pr.css\">"
    "<script src=\"/pr.js\" defer></script>";

// Full stylesheet — served from /pr.css.
constexpr char kCustomCss[] = R"CSS(
/* WiFiManager's base CSS gives every <div> `padding:5px` + `box-sizing:border-box`
   and every input/button/select `width:100%`. Custom wrapper divs would compound
   that padding, making the search box render ~20px narrower than the coord
   inputs below. Reset the paddings on our structural wrappers so widths line up. */
.pr-sec{margin:22px 0 8px;padding:0 !important}
.pr-hdr{font-size:1.05em;font-weight:700;border-bottom:1px solid #ccc;padding:0 0 3px 0 !important;margin-bottom:4px}
.pr-hint{color:#666;font-size:.85em;padding:0 !important;margin-bottom:8px}
.pr-search{position:relative;margin:5px 0 !important;padding:0 !important}
.pr-hits{display:none;position:absolute;left:0;right:0;top:100%;z-index:10;border:1px solid #ccc;border-top:none;max-height:220px;overflow:auto;font-size:.9em;background:#fff;border-radius:0 0 .3rem .3rem;box-shadow:0 3px 10px rgba(0,0,0,.12)}
.pr-hit{padding:8px 10px;cursor:pointer;border-bottom:1px solid #eee}
.pr-hit:hover{background:#e8f4fe}
.pr-hit:last-child{border-bottom:0}
.pr-chips{display:flex;flex-direction:column;gap:6px;margin:4px 0}
/* WiFiManager's stylesheet sets `input,button,select { width:100% }` — !important
   overrides are needed here or the range dropdown / remove button balloon to full
   width and squash the name input to zero. */
.pr-chip{display:flex;flex-wrap:wrap;align-items:center;gap:6px;border:1px solid #ccc;border-radius:.3rem;padding:6px 8px;background:#f4f7fa}
.pr-chip-name{flex:1 1 auto !important;min-width:6em;width:auto !important;border:0 !important;background:transparent !important;font-weight:700;font-size:1em;padding:2px 4px !important;margin:0 !important;box-sizing:border-box}
.pr-chip-name:focus{outline:1px solid #1fa3ec;border-radius:2px;background:#fff !important}
.pr-chip-range{flex:0 0 5.5em !important;width:5.5em !important;padding:2px 4px !important;font-size:.9em;margin:0 !important}
.pr-chip-rm{flex:0 0 auto !important;width:auto !important;padding:2px 10px !important;background:#dc3630 !important;color:#fff !important;border:0 !important;border-radius:.3rem !important;cursor:pointer;font-size:1em;line-height:1;margin:0 !important}
.pr-chip-sub{flex:0 0 100%;width:100%;color:#555;font-size:.8em;padding:0 4px;line-height:1.3;word-break:break-word;margin:0 !important}
.pr-chip-empty{color:#888;font-style:italic;padding:6px 4px}
.pr-saved{background:#5cb85c;color:#fff;padding:12px !important;border-radius:.3rem;margin-bottom:12px;font-weight:700;text-align:center;transition:opacity .5s}
.pr-error{background:#dc3630;color:#fff;padding:12px !important;border-radius:.3rem;margin-bottom:12px;font-weight:700;text-align:center}
/* Sticky Save button — mirrors the web app so the user doesn't have to
   scroll to the bottom of a long settings form to commit changes. */
form button[type=submit]{position:sticky !important;bottom:0 !important;z-index:5;box-shadow:0 -2px 10px rgba(0,0,0,.08)}
body.invert .pr-chip{background:#282828;border-color:#555}
body.invert .pr-chip-sub{color:#aaa}
body.invert .pr-hits{background:#282828;border-color:#555}
body.invert .pr-hit{border-bottom-color:#444}
body.invert .pr-hit:hover{background:#3a3a3a}
body.invert .pr-hdr{border-bottom-color:#555}
body.invert .pr-hint{color:#aaa}
)CSS";

// Full script — served from /pr.js.
constexpr char kCustomJs[] = R"JS(
(function(){
"use strict";
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
function deb(fn,ms){var t;return function(){var a=arguments,c=this;clearTimeout(t);t=setTimeout(function(){fn.apply(c,a);},ms);};}
function el(tag,attrs,inner){var e=document.createElement(tag);if(attrs)for(var k in attrs)e.setAttribute(k,attrs[k]);if(inner!=null)e.innerHTML=inner;return e;}

function fixCaps(){
  document.querySelectorAll('input[type=password], input[name=s], input[name=ssid]').forEach(function(x){
    x.setAttribute("autocapitalize","off");
    x.setAttribute("autocorrect","off");
    x.setAttribute("spellcheck","false");
  });
}

var apIdxP=null;
function apIdx(){
  if(apIdxP) return apIdxP;
  apIdxP=fetch("/data/airport_index.json").then(function(r){return r.ok?r.json():[];}).catch(function(){return[];});
  return apIdxP;
}
function apSearch(idx,q){
  q=q.toLowerCase();var out=[];
  for(var i=0;i<idx.length&&out.length<8;i++){
    var r=idx[i],ic=(r[0]||"").toLowerCase(),ia=(r[1]||"").toLowerCase(),ci=(r[2]||"").toLowerCase();
    var hit=ic===q||ia===q||ic.indexOf(q)===0||ia.indexOf(q)===0||ci.indexOf(q)===0||ci.indexOf(q)>=0;
    // Ported from the web app: airports with a scheduled-service IATA code
    // default to 10 nm (busy airline traffic — wider view); GA-only fields
    // without IATA default to 5 nm (tight local pattern).
    if(hit) out.push({
      label:(r[1]?r[1]+" · ":"")+r[0]+" — "+r[2],
      lat:r[3],lon:r[4],
      chipName:r[0],   // ICAO — canonical 4-letter airport id
      defaultRangeIdx:r[1]?1:0,
      subtitle:""
    });
  }
  return out;
}
function addrShortName(displayName){
  var parts=displayName.split(",").map(function(s){return s.trim();}).filter(Boolean);
  if(!parts.length) return "Place";
  var i=(/^\d+$/.test(parts[0]))?1:0;
  var pick=parts[i]||parts[0];
  return pick.length>15?pick.slice(0,15):pick;
}
function addrSearch(q,sig){
  return fetch("https://radar.benyaffe.com/api/geocode?q="+encodeURIComponent(q),{signal:sig})
    .then(function(r){return r.ok?r.json():[];})
    .then(function(rows){return rows.slice(0,5).map(function(x){return{
      label:"📍 "+x.display_name,
      lat:x.lat,lon:x.lon,
      chipName:addrShortName(x.display_name),
      subtitle:x.display_name
    };});})
    .catch(function(){return[];});
}
function search(q){
  if(q.length<2) return Promise.resolve([]);
  var ac=new AbortController();
  return Promise.all([
    apIdx().then(function(i){return apSearch(i,q);}),
    q.length>=3?addrSearch(q,ac.signal):Promise.resolve([])
  ]).then(function(rs){return rs[0].concat(rs[1]);});
}

// Find the <label for=id> that matches this input, walking past any <br>s.
// Rejects a label that belongs to a different field (checkboxes use
// label-AFTER so their `previous` chain leads to the prior field's label —
// which was the source of the earlier "search box swallowed the label" bug).
function labelFor(input){
  var e=input.previousElementSibling;
  while(e && e.tagName==="BR") e=e.previousElementSibling;
  if(e && e.tagName==="LABEL" && e.getAttribute("for")===input.id) return e;
  return null;
}
function anchorFor(input){
  var lbl=labelFor(input);
  if(lbl) return lbl;
  var prev=input.previousElementSibling;
  if(prev && prev.tagName==="BR") return prev;
  return input;
}
function makeSection(title,hint){
  var s=el("div",{"class":"pr-sec"});
  s.appendChild(el("div",{"class":"pr-hdr"},esc(title)));
  if(hint) s.appendChild(el("div",{"class":"pr-hint"},esc(hint)));
  return s;
}
function makeSearchBox(placeholder){
  var box=el("div",{"class":"pr-search"});
  box.innerHTML=
    '<input type="text" placeholder="'+esc(placeholder)+'" style="width:100%;padding:5px;font-size:1em" autocapitalize="off" autocorrect="off" spellcheck="false">'+
    '<div class="pr-hits"></div>';
  return box;
}
function renderHits(hits,results,pick){
  if(!results.length){hits.style.display="none";hits.innerHTML="";return;}
  hits.innerHTML=results.map(function(r,i){return '<div class="pr-hit" data-i="'+i+'">'+esc(r.label)+'</div>';}).join("");
  hits.style.display="block";
  hits.querySelectorAll(".pr-hit").forEach(function(x){
    x.addEventListener("click",function(){pick(results[+x.getAttribute("data-i")]);});
  });
}

// Insert a section header + search box above the coord pair, using the
// matched <label for=id> as the anchor so the header lands above the label
// (not between the label and the input).
function decorateCoordPair(latEl,lonEl,title,hint){
  var anchor=anchorFor(latEl);
  var sec=makeSection(title,hint);
  var box=makeSearchBox("Search address or airport (e.g. SFO, Golden Gate Bridge)");
  sec.appendChild(box);
  anchor.parentNode.insertBefore(sec,anchor);
  var input=box.querySelector("input"),hits=box.querySelector(".pr-hits");
  var run=deb(function(){
    search(input.value.trim()).then(function(rs){
      renderHits(hits,rs,function(r){
        latEl.value=Number(r.lat).toFixed(6);
        lonEl.value=Number(r.lon).toFixed(6);
        input.value=r.subtitle||r.chipName;
        hits.style.display="none";
        latEl.dispatchEvent(new Event("input"));
        lonEl.dispatchEvent(new Event("input"));
      });
    });
  },300);
  input.addEventListener("input",run);
  document.addEventListener("click",function(e){if(!sec.contains(e.target)) hits.style.display="none";});
}
function insertHeaderBefore(anchor,title,hint){
  if(!anchor) return null;
  var sec=makeSection(title,hint);
  anchor.parentNode.insertBefore(sec,anchor);
  return sec;
}

function decorateFocusEditor(field){
  // Client-side cap — must match config::kMaxFocusAirports in include/config.h.
  // The firmware also enforces this server-side; this is the friendly UI cap.
  var MAX_AIRPORTS=6;
  var anchor=anchorFor(field);
  var sec=makeSection("Focus places","Extra spots the radar cycles through with a double-tap.");
  var chips=el("div",{"class":"pr-chips"});
  sec.appendChild(chips);
  var box=makeSearchBox("Add airport or address (e.g. PAO, Golden Gate Bridge)");
  sec.appendChild(box);
  var capHint=el("div",{"class":"pr-hint","style":"display:none;margin-top:4px;font-size:0.85em;opacity:0.75"},
    "Max "+MAX_AIRPORTS+" focus airports — remove one to add another.");
  sec.appendChild(capHint);
  anchor.parentNode.insertBefore(sec,anchor);
  // Hide the raw JSON textarea and its label — chips are the source of truth
  // from the user's perspective; the field is a hidden save-handler pipe.
  if(anchor.tagName==="LABEL") anchor.style.display="none";
  field.style.display="none";

  var input=box.querySelector("input"),hits=box.querySelector(".pr-hits");
  var rng=[5,10,15,25]; // matches kRangePresets in include/ui/radar_range.h
  var arr=[];
  try{arr=JSON.parse(field.value||"[]");if(!Array.isArray(arr))arr=[];}catch(e){arr=[];}
  arr.forEach(function(e){e._sub=e._sub||"";});

  function ser(){
    field.value=JSON.stringify(arr.map(function(e){return{
      name:String(e.name||"").slice(0,15),
      lat:+Number(e.lat).toFixed(6),
      lon:+Number(e.lon).toFixed(6),
      range_idx:e.range_idx|0
    };}));
  }
  function migrateIata(){
    var hasIata=arr.some(function(e){return typeof e.name==="string"&&e.name.length===3;});
    if(!hasIata) return;
    apIdx().then(function(idx){
      var byIata={};
      idx.forEach(function(r){if(r[1]) byIata[r[1].toUpperCase()]=r[0];});
      var changed=false;
      arr.forEach(function(e){
        if(typeof e.name==="string" && e.name.length===3){
          var up=byIata[e.name.toUpperCase()];
          if(up){e.name=up;changed=true;}
        }
      });
      if(changed){draw();ser();}
    });
  }
  function updateCapHint(){
    capHint.style.display=(arr.length>=MAX_AIRPORTS)?"block":"none";
  }
  function draw(){
    chips.innerHTML="";
    updateCapHint();
    if(!arr.length){
      chips.appendChild(el("div",{"class":"pr-chip-empty"},"No focus places yet — search below to add one, or reboot to pull in the defaults."));
      return;
    }
    arr.forEach(function(e,i){
      var chip=el("span",{"class":"pr-chip","data-i":i});
      var opts=rng.map(function(nm,ri){return '<option value="'+ri+'"'+(ri===(e.range_idx|0)?" selected":"")+">"+nm+" nm</option>";}).join("");
      chip.innerHTML=
        '<input class="pr-chip-name" value="'+esc(e.name)+'" maxlength="15" autocapitalize="off" autocorrect="off" spellcheck="false">'+
        '<select class="pr-chip-range">'+opts+'</select>'+
        '<button type="button" class="pr-chip-rm" title="Remove">×</button>'+
        (e._sub?'<div class="pr-chip-sub">'+esc(e._sub)+'</div>':'');
      chip.querySelector(".pr-chip-name").addEventListener("input",function(ev){arr[i].name=ev.target.value;ser();});
      chip.querySelector(".pr-chip-range").addEventListener("change",function(ev){arr[i].range_idx=+ev.target.value;ser();});
      chip.querySelector(".pr-chip-rm").addEventListener("click",function(){arr.splice(i,1);draw();ser();});
      chips.appendChild(chip);
    });
  }
  draw();ser();migrateIata();

  var run=deb(function(){
    search(input.value.trim()).then(function(rs){
      renderHits(hits,rs,function(r){
        if(arr.length>=MAX_AIRPORTS){
          input.value="";hits.style.display="none";updateCapHint();
          return;
        }
        arr.push({
          name:String(r.chipName).slice(0,15),
          lat:+Number(r.lat).toFixed(6),
          lon:+Number(r.lon).toFixed(6),
          range_idx:(typeof r.defaultRangeIdx==="number")?r.defaultRangeIdx:1,
          _sub:r.subtitle||""
        });
        input.value="";hits.style.display="none";draw();ser();
      });
    });
  },300);
  input.addEventListener("input",run);
  document.addEventListener("click",function(e){if(!sec.contains(e.target)) hits.style.display="none";});
}

function autoLocate(latEl,lonEl){
  if(!latEl||!lonEl) return;
  var la=parseFloat(latEl.value),lo=parseFloat(lonEl.value);
  if(!isNaN(la)&&!isNaN(lo)&&!(la===0&&lo===0)) return;
  fetch("https://ipapi.co/json/").then(function(r){return r.ok?r.json():null;}).then(function(d){
    if(!d||typeof d.latitude!=="number"||typeof d.longitude!=="number") return;
    if(parseFloat(latEl.value)===0||latEl.value==="") latEl.value=d.latitude.toFixed(6);
    if(parseFloat(lonEl.value)===0||lonEl.value==="") lonEl.value=d.longitude.toFixed(6);
  }).catch(function(){});
}

// In-place save: intercept the /paramsave form submit, POST the form data
// via fetch, and drop a "Saved ✓" banner at the top of the page. No
// navigation, no dead-end WiFiManager confirmation page.
function showBanner(cls,text){
  var wrap=document.querySelector(".wrap")||document.body;
  var b=el("div",{"class":cls},esc(text));
  wrap.insertBefore(b,wrap.firstChild);
  window.scrollTo({top:0,behavior:"smooth"});
  setTimeout(function(){
    b.style.opacity="0";
    setTimeout(function(){if(b.parentNode) b.parentNode.removeChild(b);},600);
  },2500);
}
function interceptSave(){
  var form=document.querySelector("form[action*='paramsave'],form[action='paramsave']");
  if(!form) return;
  form.addEventListener("submit",function(ev){
    ev.preventDefault();
    var btn=form.querySelector("button[type=submit],button");
    if(btn) btn.disabled=true;
    var data=new FormData(form);
    var body=new URLSearchParams();
    data.forEach(function(v,k){body.append(k,v);});
    fetch(form.action,{method:"POST",body:body,headers:{"Content-Type":"application/x-www-form-urlencoded"}})
      .then(function(r){
        if(r.ok||r.status===200||r.status===302){
          // Device auto-restarts after saving so new focus / home coords
          // pick up their tiles via the boot-time sync fetch. Show a
          // second banner + auto-reload the page once the device is back
          // (roughly 8-10 s: reboot + Wi-Fi rejoin + LAN portal restart).
          showBanner("pr-saved","Saved ✓ — device restarting");
          setTimeout(function(){
            showBanner("pr-saved","Reconnecting…");
            setTimeout(function(){window.location.href="/param";},4000);
          },4000);
        }else showBanner("pr-error","Save failed — "+r.status);
      })
      .catch(function(){
        // A dropped connection immediately after POST is EXPECTED — the
        // device rebooted while our fetch was in flight. Still success.
        showBanner("pr-saved","Saved ✓ — device restarting");
        setTimeout(function(){
          showBanner("pr-saved","Reconnecting…");
          setTimeout(function(){window.location.href="/param";},4000);
        },4000);
      })
      .finally(function(){if(btn) btn.disabled=false;});
  });
}

// Cancel = revert any local edits (chip additions, coord edits, layer toggle
// clicks) by reloading /param from the server. Matches the web dialog's
// Cancel button. Inserted next to Save.
function addCancelButton(){
  var form=document.querySelector("form[action*='paramsave'],form[action='paramsave']");
  if(!form) return;
  var save=form.querySelector("button[type=submit]");
  if(!save) return;
  var cancel=el("button",{"type":"button","class":"pr-cancel"},"Cancel");
  cancel.style.cssText="background:#777 !important;margin-top:6px !important";
  cancel.addEventListener("click",function(){
    window.location.href="/param";  // force fresh server-state fetch
  });
  save.parentNode.insertBefore(cancel,save.nextSibling);
}

// Reset all settings = POST /reset-settings on the device. Clears the
// non-Wi-Fi NVS namespaces (home, METAR, focus ring, layers, range) and
// reboots. Confirms first — this is destructive.
function addResetButton(){
  var host=document.querySelector("input[name=ota_host]");
  if(!host) return;
  var anchor=anchorFor(host);
  var box=el("div",null,"");
  box.style.cssText="margin-top:12px";
  box.innerHTML='<button type="button" class="pr-reset" style="background:#dc3630 !important">Reset all settings</button>'+
                '<div class="pr-hint" style="margin-top:4px">Clears home, weather map, focus places, layers. Wi-Fi credentials stay.</div>';
  // Insert AFTER the hostname field group — walk forward past the input.
  var afterHost=host.nextSibling;
  while(afterHost && afterHost.nodeType===3) afterHost=afterHost.nextSibling; // skip text nodes
  if(afterHost) host.parentNode.insertBefore(box,afterHost);
  else host.parentNode.appendChild(box);
  box.querySelector(".pr-reset").addEventListener("click",function(){
    if(!confirm("Reset home, weather map, focus places, and layers to defaults? Wi-Fi will stay connected.")) return;
    var btn=box.querySelector(".pr-reset");
    btn.disabled=true;btn.textContent="Resetting…";
    fetch("/reset-settings",{method:"POST"})
      .then(function(r){
        if(!r.ok) throw new Error("reset failed: "+r.status);
        showBanner("pr-saved","Reset ✓ — device rebooting");
        setTimeout(function(){window.location.href="/";},2500);
      })
      .catch(function(err){
        showBanner("pr-error","Reset failed — "+err.message);
        btn.disabled=false;btn.textContent="Reset all settings";
      });
  });
  // Avoid the sticky-save shadow rendering on top of our reset button.
  anchor; // silence unused
}

function updateBranding(){
  var captive=/^192\.168\.4\.1/.test(window.location.host)||/plane-?radar[-.]setup/i.test(window.location.host);
  document.title=captive?"Plane Radar — Setup":"Plane Radar";
  var h1=document.querySelector("h1");
  if(h1) h1.textContent=captive?"Plane Radar Setup":"Plane Radar";
  // Root menu (/) button relabels — WiFiManager's stock labels are terse and
  // don't say "Plane Radar" anywhere. Match the button to what it opens.
  document.querySelectorAll("form").forEach(function(f){
    var a=f.getAttribute("action")||"";
    var btn=f.querySelector("button");
    if(!btn) return;
    if(a.indexOf("/param")>=0 && btn.textContent.trim()==="Setup") btn.textContent="Plane Radar Setup";
  });
}

function init(){
  updateBranding();
  fixCaps();
  var lh=document.querySelector("input[name=radar_lat]");
  var oh=document.querySelector("input[name=radar_lon]");
  var lm=document.querySelector("input[name=metar_lat]");
  var om=document.querySelector("input[name=metar_lon]");
  var rm=document.querySelector("input[name=metar_rad]");
  var fr=document.querySelector("textarea[name=focus_ring],input[name=focus_ring]");
  var lyr1=document.querySelector("input[name=lyr_coast]");
  var host=document.querySelector("input[name=ota_host]");
  if(lh&&oh) decorateCoordPair(lh,oh,"Home","Where the radar is centered by default.");
  if(lm&&om) decorateCoordPair(lm,om,"Weather map","Center of the weather-color airport dot map.");
  if(rm){
    var reachAnchor=anchorFor(rm);
    if(reachAnchor){
      var h=el("div",{"class":"pr-hint"},"How far the weather map reaches from that center.");
      reachAnchor.parentNode.insertBefore(h,reachAnchor);
    }
  }
  if(fr) decorateFocusEditor(fr);
  if(lyr1) insertHeaderBefore(anchorFor(lyr1),"Map layers","Turn each overlay on or off.");
  if(host) insertHeaderBefore(anchorFor(host),"Device","Advanced — change if you have more than one radar on your network.");
  if(lh&&oh) autoLocate(lh,oh);
  interceptSave();
  addCancelButton();
  addResetButton();
}

if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",init); else init();
})();
)JS";

}  // namespace plane_radar::portal
